#!/bin/sh
cd frameworks/av
git apply -v ../../device/TCL/5010D/patches/framework_av/0001-libmedia-stub-out-MTK-specific-bits-audio-working.patch

# undo patch
# cd frameworks/av
# git checkout .
# rm media/libmedia/mtkaudio_stubs.cpp


